### ISSUE TITLE
Name the data in MetaData.csv and Schedule.csv

### ISSUE THREAD

**Issue by amalp12** [Janmejay-Joshi/Auto-Attendance-Moodle#2]
It would be really helpful for the users of this code if you could explain in the readme.txt, what each column/row in MetaData.csv and Schedule.csv means and what they refer to. Thank You.

**Comment by Janmejay-Joshi** [comment]
Thanks for the reminder was meaning to add it.

Fixed in 658290380fb234bb2e2fe27df3ccf32d80eedd02
